env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2018
rules:
  indent: ["error", 2]
  quotes:
    - 2
    - 'single'
  semi: 2
  no-extra-semi: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 1
  no-unreachable: 1
  valid-typeof: 2
  use-isnan: 2
  no-unsafe-negation: 2
  array-callback-return: 1
  block-scoped-var: 1
  complexity: 2
  consistent-return: 1
  eqeqeq: 2
  no-else-return: 1
  no-new-wrappers: 2
  no-return-await: 2
  array-bracket-spacing: 2
  block-spacing: 2
  brace-style: 2
  comma-dangle:
    - 2
    - 'never'
  no-lonely-if: 2
  semi-style: 2
  no-var: 2
  no-unused-vars: 1
  prefer-const: 2
  prefer-destructuring: 2
  # arrow-parens: 2 # The jury is out on this one
  object-curly-spacing:
    - 2
    - 'always'
  space-before-blocks:
    - 2
    - 'always'
